stages:
  - env-creation
  - prepare-${{values.awsEnvironmentName}}-stage
  - ${{values.awsEnvironmentName}}-stage

variables:
  APP_KEBAB_NAME: "${{ values.kebabName }}"
  APP_SHORT_NAME: "${{ values.component_id }}"
  APP_TEMPLATE_NAME: "example-serverless-rest-api"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"

include:
  - project: 'opa-admin/backstage-reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-job-defaults-cdk.yml'
      - 'common/cicd/.gitlab-ci-aws-base.yml'
      - 'common/cicd/.gitlab-ci-aws-iac-serverless-api.yml'
