apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Values.configMap.name }}
 namespace: {{ .Values.namespace }}
 labels:
    {{- include "${{ values.component_id }}.labels" . | nindent 4 }}
data:
  ENVIRONMENT_NAME: {{ .Values.opa.environmentName }}
