apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.nsAdminRoleBinding.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "${{ values.component_id }}.labels" . | nindent 4 }}
subjects:
- kind: User
  name: {{ .Values.appAdminRole }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

