apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "${{ values.component_id }}.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "${{ values.component_id }}.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  type: NodePort
