apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-engineering-with-backstage
  annotations:
    github.com/project-slug: shazi7804/platform-engineering-with-backstage
spec:
  type: service
  lifecycle: production
  owner: admin
