apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ values.component_id }}-admin
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/env: ENV_PLACEHOLDER

