apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.component_id }}-sa
  labels:
    app.kubernetes.io/env: ENV_PLACEHOLDER
  annotations:
    eks.amazonaws.com/role-arn: SA_ROLE_PLACEHOLDER

