apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${{ values.component_id }}-view-ns
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/env: overrideMe
subjects:
- kind: User
  name: APP_ADMIN_ROLE_PLACEHOLDER
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: opa-namespace-viewer
  apiGroup: rbac.authorization.k8s.io
