apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.component_id }}-sa
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/env: overrideMe
  annotations:
    eks.amazonaws.com/role-arn: overrideMe
