apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.component_id | dump }}
  title: ${{ values.title | dump }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - aws
    - rds
    - aws-resource
    - database
  annotations:
  iacType: cdk
  resourceType: "aws-rds"
  dbName: ${{ values.dbName | dump }}
  dbObjectName: ${{ values.dbObjectName | dump }}
  awsArn: ""
spec:
  type: aws-resource
  subType: "arn:aws:rds"
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
  dependsOn: []
