apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}-mainpod
  labels:
    app.kubernetes.io/env: ENV_PLACEHOLDER
spec:
  selector:
    matchLabels:
      app.kubernetes.io/env: ENV_PLACEHOLDER
  template:
    metadata:
      labels:
        app.kubernetes.io/env: ENV_PLACEHOLDER
    spec:
      serviceAccountName: ${{ values.component_id }}-sa
      containers:
      - name: webapp
        image: ACCT_PLACEHOLDER.dkr.ecr.REGION_PLACEHOLDER.amazonaws.com/${{ values.component_id }}-ENV_PLACEHOLDER-ENV_PROVIDER_PLACEHOLDER:latest
        envFrom:
          - configMapRef:
              name: ${{ values.component_id }}-env-vars
