apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ values.component_id }}-admin
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/env: overrideMe
subjects:
- kind: User
  name: APP_ADMIN_ROLE_PLACEHOLDER
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
