apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl.owner + "/" + values.repoUrl.repo }}
  title: ${{"Amazon EC2 Instance/" + values.InstanceName }}
  description: An example of a Instance Creation.
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
