apiVersion: aws.backstage.io/v1alpha
kind: AWSEnvironmentProvider
metadata:
  name: ${{ values.name | dump }}
  title: ${{ values.title | dump }}
  prefix: ${{values.prefix | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  tags:
    - aws
    - aws-environment-provider
    - eks
  envType: ${{values.envType}}
  awsAccount: "${{values.awsAccount}}"
  awsRegion: ${{values.awsRegion}}
  environmentRole: "${{values.environmentRole}}"
  apiAccess: "${{values.apiAccess}}"
  apiAccessCidrs: "${{values.apiAccessCidrs}}"
  nodeType: "${{values.nodeType}}"
  vpc: ""
  clusterName: ""
  operationRole: ""
  provisioningRole: ""
  auditTable: ""
  clusterAdminRole: ""
  kubectlLambdaArn: ""
  kubectlLambdaAssumeRoleArn: ""

spec:
  type: environment-provider
  lifecycle: experimental
  owner: ${{values.owner | dump}}
