image: node:18
variables:
  AWS_ACCOUNT: "${{ values.aws_account }}"
  AWS_DEFAULT_REGION: "${{ values.aws_region }}"
  ROLE_ARN: "${{values.environment_role}}"
  OPA_PLATFORM_REGION: "${{ values.platform_region }}"
  
stages:
  - build

include:
  - project: 'opa-admin/backstage-reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-aws-provider-basic.yml'
