apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: sagar0419/aws-ec2 # name of the terraform repo
    backstage.io/techdocs-ref: dir:.
  title: 'IA for Instance Automation'
  description: An example of a Instance Creation.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
