apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: An example of a repository creation.
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
