apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}-service
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/env: overrideMe
spec:
  selector:
    app.kubernetes.io/name: ${{ values.component_id }}
  ports:
    - name: http
      port: 80
      targetPort: ${{ values.appPort }}
      protocol: TCP
  type: NodePort
